### PR TITLE
proposal: make epic image the background (see result)

### PR DESCRIPTION
**Pull request by SeanHollen**
This is an example pull request

### CODE REVIEW

**Review by ralamo33 — COMMENTED** [review]
If you want monster.js to be its own page it needs to be under src/pages

Could you add a picture of how the website looks with the changes?

**Comment by SeanHollen** [comment]
Here's an image, I think it's pretty awesome.

________________________________

**Comment by SeanHollen** [comment]
(Monster page is blank for now) 
What the site looks like (I think pretty awesome): 
Screen Shot 2021-02-23 at 5 08 30 PM

**Comment by ralamo33** [comment]
Looks sick dude nice work!

**Pull request merged**
